### ISSUE TITLE
Some refactoring

### ISSUE THREAD

**Issue by bantierr** [cascade-artifacts-designs/cascade-meta#12]
Hi Flavien,
To try and not forget too much about Cascade, I did some refactoring. I am not sure if you find it useful, but here is the code if you are interested. If I have time I might even try to make a cool TUI :)

I have tested the code without any issue on 1000 elf files. The main benefit of the current refactor is that steps to generate basic block in the main basic block loops are nicely split in smaller steps. I've also added a few getter and setter methods to the fuzzerstate.

Here is the link to my fork: [https://github.com/bantierr/cascade-meta.git ](https://github.com/bantierr/cascade-meta.git)

Best,
Quentin

**Comment by flaviens** [comment]
Hi Quentin, thanks! Much appreciated. Can you please create a pull request?
