### ISSUE TITLE
Wrong parameter when setting PMPADDR0 in initialblock.py

### ISSUE THREAD

**Issue by zhangkanqi** [cascade-artifacts-designs/cascade-meta#14]
Hi, @flaviens 

Is there a typo here? I think the third parameter should be `1` rather `0`.

https://github.com/cascade-artifacts-designs/cascade-meta/blob/8834d6bdd887e2293849b046db16d5185c5319db/fuzzer/cascade/initialblock.py#L68

**Comment by flaviens** [comment]
Hi @zhangkanqi , thanks for pointing this out! While it looks weird, this typo should be without effect given that the top 10 bits of `pmpaddr` registers are WARL equal to zero (or might reveal a bug in the CPU implementation of that register ;) ). That said, I'll fix it to 1 to make it cleaner. The line could as well be removed. Thanks!

Out of curiosity, did you notice this by manually going through the code or did you encounter a bug in a CPU that does not correctly implement this?

![spec screenshot](https://github.com/user-attachments/assets/07077ae4-a93d-4fad-b2bc-e1db1781c663)

**Comment by flaviens** [comment]
Thanks! Appreciated. Indeed:
(1) Virtual addresses are not yet supported.
(2) Not all exceptions are supported at the moment.
