### ISSUE TITLE
How to obtain ASM files in the process of do_genmanyelfs.py

### ISSUE THREAD

**Issue by dw763j** [cascade-artifacts-designs/cascade-meta#15]
Hi there, thanks for your great work!

I successfully ran the process of do_genmanyelfs.py and gain the elf files, yet I want to further get the original ASM files for these ELFs.
Any suggestions for that?

Thanks again~

**Comment by flaviens** [comment]
Hi @dw763j ,
Thanks for reaching out!
You can use objdump from the riscv-gcc toolchain to get a dump.
I haven't seen any use case of reverting back to assembly+linker script (cascade directly creates ELF files without calling a compiler or linker) but I can imagine it could be potentially beneficial. This feature does not yet exist but if you'd like to implement it, I'm happy to assist you!

**Comment by dw763j** [comment]
Hi, @flaviens,
Thanks for your reply, actually I want to leaverage the capability of cascade for generating asm for diff test in another framework, if not officially implemented, I shall just make objdump as you said.
Thanks for your help.
