### ISSUE TITLE
Seemingly illegal instructions?

### ISSUE THREAD

**Issue by mysoreanoop** [cascade-artifacts-designs/cascade-meta#2]
When I objdump the generated ELF for default (BOOM) design, I see the dump contains frequent, interceding `.4byte` lines between instructions like so:
```
...
    800000ee:   c05e                    sw      s7,0(sp)
    800000f0:   fc22                    sd      s0,56(sp)
    800000f2:   801abd43                fmadd.s fs10,fs5,ft1,fa6,rup
    800000f6:   7ff535c7                .4byte  0x7ff535c7
...
```
... which are also not in the fall through of a preceding jump instruction either. However, I don't see BOOM failing on those, though I haven't been able to generate a Verilated model which traces executed instructions. Do you have any insight on why I'm seeing those?

**Comment by mysoreanoop** [comment]
It doesn't seem to be a legal instruction -- unless it's a custom instruction? 
I'm not sure if you could embed data between instructions like that, but even then, it's not supposed to be reachable in normal execution, right?

Also, have you been able to generate the tracing version of the Verilator executable for BOOM/Rocket? 

By inconveniences, do you mean potentially the objdump is not recognizing it? I am using the unmodified `riscv64-unknown-elf-objdump -D elf_file`

**Comment by flaviens** [comment]
Hi @mysoreanoop,

It should be an instruction for sure.
You may check in the `fuzzerstate.instr_objs_seq` structure (which is a list of basic blocks, themselves lists of instructions) what is the intended instruction type if this can help.

> By inconveniences, do you mean potentially the objdump is not recognizing it?

Exactly. I never took the time to make it perfectly nice for humans to read.

> Also, have you been able to generate the tracing version of the Verilator executable for BOOM/Rocket?

[You can follow the instructions here](https://github.com/comsec-group/cascade-artifacts/issues/9#issuecomment-1970835810) to get hardware traces.

Thanks!

**Comment by mysoreanoop** [comment]
You're right, seems like `fmsub.q`
```
0x7ff535c7
0111 1111 1111 0101 0011 0101 1100 0111
      ^^             ^^^       ^^^ ^^^^
    quad.          round up.   
```
![image](https://github.com/cascade-artifacts-designs/cascade-meta/assets/29160122/31613476-5b71-4966-9a75-ff5c118ff648)

I don't see that anywhere in the instruction opcode selection when I grep it (I see other instructions clearly though). Do you see anything off here?

**Comment by flaviens** [comment]
Hi @mysoreanoop,

Thank you for your message!
I did not really understand your question, my apologies. Could you please reformulate?

Thanks!

**Comment by mysoreanoop** [comment]
Sorry, please correct me if I'm wrong here. 
I see that the Q extension (for quad-precise FP instructions like the one in discussion) is not enabled in meta/cfg.json.
Plus, I also don't see any quad instruction strings being generated in the python code either when I grep it. But still I see those instructions in the dump -- which I cannot understand how.

**Comment by flaviens** [comment]
Thank you @mysoreanoop  for your message!
Did you get a chance to look at the entry in `fuzzerstate.instr_objs_seq`? This will tell you Cascade's intent with this instruction.

**Comment by flaviens** [comment]
I close this issue since no response since more than a month. Feel free to reopen if your issue persists!
