### ISSUE TITLE
ELF init error

### ISSUE THREAD

**Issue by Donkey-Hao** [cascade-artifacts-designs/cascade-meta#9]
Hi, thanks for your great work, I want to use `do_genmanyelfs.py` to gen some elf files, but the error occurred:
```zsh
➜  fuzzer git:(master) ✗ python3 do_genmanyelfs.py 1000 /home/elf/
Traceback (most recent call last):
  File "/home/cascade-meta/fuzzer/do_genmanyelfs.py", line 25, in <module>
    gen_many_elfs('rocket', num_cores, num_elfs, target_dir)
  File "/home/cascade-meta/fuzzer/analyzeelfs/genmanyelfs.py", line 51, in gen_many_elfs
    calibrate_spikespeed()
  File "/home/cascade-meta/fuzzer/common/spike.py", line 270, in calibrate_spikespeed
    gen_elf(rv32i_jal(0, 0).to_bytes(4, 'little'), SPIKE_STARTADDR, SPIKE_STARTADDR, elfpath, False)
  File "/home/cascade-meta/fuzzer/common/bytestoelf.py", line 21, in gen_elf
    elf = ELF(e_machine=243, e_data=ELFDATA.ELFDATA2LSB, e_entry=start_addr)
TypeError: ELF.__init__() got an unexpected keyword argument 'e_entry'
```
And I checked the `makeelf` code, the [ELF class init function](https://github.com/v3l0c1r4pt0r/makeelf/blob/master/makeelf/elf.py#L118) do not have the argument `e_entry`. The `makeelf` version is 0.3.4, how can I fix this problem to get some elf files.
```python
    def __init__(self, e_class=ELFCLASS.ELFCLASS32, e_data=ELFDATA.ELFDATA2MSB,
            e_type=ET.ET_EXEC, e_machine=EM.EM_NONE):
```
Great thanks.

**Comment by TobiasKovats** [comment]
Hi Donkey-Hao!

Thanks for trying Cascade!
It seems that you are not using the [fork](https://github.com/flaviens/makeelf.git) referenced in the repository. Please ensure that you are using the toolchain as referenced by their respective submodule repositories in the _tools_ directory.

Hope this helps.

Greetings,
Tobias

**Comment by Donkey-Hao** [comment]
Hi @TobiasKovats 
I did not notice the *tools* directory. Thanks for your help. 

Best wishes.
Hao
